### ISSUE TITLE
Reaction display is broken.

### ISSUE THREAD

**Issue by Sekir0** [ghosts-network/web-spa#59]
**Describe the bug**
Reaction display is broken.

**To Reproduce**
1. Go to any publication
2. Click on 2-3 different reaction
4. Now u can see problem with reactions. Displayed only "Like" reaction. If you choose any another reaction "Like" will displeyed multiple times. If you delete your reaction and then leave a reaction again, a multiple "Like" will remain

**Expected behavior**
The reaction left by the user should be displayed correctly.
Also, each reaction should only be displayed once.

**Screenshots**
![alt text](https://lh3.googleusercontent.com/FXsEzhvK3mGE2YTdPV8YPVZeX1MWdJayqFgkvv6lOD-A33K9ppJfh7hpFXCHbUZ9BLwv2O7eFxoYHELuU7qMVaBi2TX4JvDJQQOA5I4AC-cF_WLZ4HbTTXYGXrQQ1s0bJRNaIDvKky6xOYN4_3LU_ZN6QJjUozMgey_12vtP8GdenJjzZbdmZV4nu0rflSzxi4fWCB4KKRwWJ0B2rZaJtsYhjIGTH3HNClwNDwBNUyuDYLxirnls2GqWOgLxMqHUGqKIMvTYkYMWOY5j0Zlgf60yy8eZw_-VeHM4Zw-sMYm6pgwphBoO3QsSN8jy3PwHwqPy3JhGnj2Za9cqiUngQ-nEmtod-09KutNzts81jWokMlFnaP8hz9MXrgJL9FZywVZgkPdWqBGkePJa5JDb9IQxBwEmdRpV8LmpiRDPiITFgohsPNxF8uCVkhGxxFyzoDsGCl7Ve0_LJ6OhRnT6Bg0RHNDeiCxEYeWJPTZaon3W229P9aOHRm-j3XHbk05h_cIrQhARbtGoBQU8YSINLNclCVvKt6Obg1OIfw7MZX46v61sVDsFFK3M340DbWQNnfYYqS6lx5yZI5Y3SEBVq1iwccgEafukjbkh8u3CsNaJkBFXf3CgqyGCHVV-RwnheWj576cMqX5Fvt57eR7Nud902b9Xp3vtgsVcZzb21TD5wgNpq-dA6-vAGL3hIabMCqxtMm9SvNbe41dxwgPm49nq44145QDq6PfqCKpkfarUkIBxemHbMBI725M=w262-h99-no?authuser=0)

![alt text](https://lh3.googleusercontent.com/aOI-TfwW_jd49Py_hTpkor4Pp5O2JASUKdClHPQIIy9taKyZRpgYbTDEhvUZDQa-T-2GK4uAV6hQ44wwJR6P4OpTzqJKn-m-9pDLLY8hrb0hn9itzXeuNuUvMxQsLSwSn5Gv0QX_2G0ZgBZ1mOhIMTHfQMu35wGlKop_nV4an20zWG61E8gCTHIHxRWzHRN9AM7Ljwar1SoIbgVJVV9HRGiYWXfwBeAFuQ2NgBcj6hGCs9CBtXv36Y3PeeDizcLa6UY5QSX4HOfCtzv9EQP68Scn7E9BSnCZrWJVP6zegTkLRdZf2d0N99ZD21M2r5lUPEwMwr893xFnm-6NZZEHaIwVn7LWHUAsDY3jiz4CK9mUUp0oWCN4JZV2z6UaKihwkzqrYdqLJWNqm2ktLYrSUJoq1Jb6hDsjEwv1iWVZSLRLDOT8lSVZerquP82xe7uyF8EMHD9C1JKpW5HVpO6o8GkECWk15UoOOyegKVa6gq_lTZRNpXPFT_qkLohlQ3eThpqXjD12NUYFFq2rCmHWVDkGJInm-iJ_Wpq1TyXl8W_SAs-Wr52R5Lre7ptjLo-pY2WPWrXwyXvTXVfF4PEHg3SlC9b8VDZccwnmsVn8pfMedy_rqd8UUmp0ZJGhZpszHzMyBM33DqO0yx62a9StX_cquDMkMNlL_byN5YKar9TiacmNzkrC78TVbGeB8drHjuXtGlqdJyNQ3I4hYJ__D2Lmwm0dwVk2gBTRr2o9PAUMLCUxKloL8RSNQm0=w252-h97-no?authuser=0)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 105.0.5195.102

**Comment by volodymyr-borodin** [comment]
Done

**Comment by Sekir0** [comment]
Best!
